#ifndef __PUNCH_OUT_RESOURCES__
#define __PUNCH_OUT_RESOURCES__

enum PUNCH_OUT_TEXTURES
{
    BOXER_LIL_MAC_TEXTURE,
    BOXER_GLASS_JOE_TEXTURE,
    RING_RING_BACKGROUND,
    FIGHT_REFEREE_TEXTURE,
    MENU_TITLE_SCREEN,
    MENU_NEW_GAME,
    MENU_CONTINUE,
    MENU_GLOVE,

};
enum PUNCH_OUT_SOUND
{
    MAC_DODGE_CHUNK,
    MAC_PUNCH_CHUNK,
    MAC_PUNCH_BLOCKED_CHUNK,
    CROWD_CHEER_CHUNK,
    GLASS_JOE_THEME,
    FIGHT_THEME,
    OPPONENT_PUNCH,
    BELL_RING

};

#endif